# timer_app/migrations/0001_initial.py

# Generated by Django 4.2.7 on 2023-06-18 00:00

from django.db import migrations, models
import shortuuid

def generate_short_uuid():
    return shortuuid.uuid()[:8]

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(unique=True)),
                ('user_code', models.CharField(default=generate_short_uuid, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]