# Generated by Django 5.2.3 on 2025-06-25 17:38

import timer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default=timer_app.models.generate_short_uuid, max_length=16, unique=True),
        ),
    ]
